// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: fsae-laptimer.spjj

#include "ui.h"
#include "../main/fsaeEvents.h"

void accelResetClicked(lv_event_t * e)
{
	fsaeAccel_reset();
}

void skidResetClicked(lv_event_t * e)
{
	fsaeSkid_reset();
	// Your code here
}

void accelScreenLoaded(void)
{
	fsaeAccel_init();
}

void skidScreenLoaded(void)
{
	fsaeSkid_init();
}
