// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: fsae-laptimer.spjj

#include "../ui.h"
#include <stdio.h>
#include <stdbool.h>

lv_obj_t * uic_accelTime;
lv_obj_t * uic_accelReset;
lv_obj_t * uic_accelPhotoGate2Status;
lv_obj_t * uic_accelPhotoGate1Status;
lv_obj_t * uic_accelScreen;
lv_obj_t * ui_accelScreen = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_home2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_accelPhotoGate1Status = NULL;
lv_obj_t * ui_accelPhotoGate2Status = NULL;
lv_obj_t * ui_accelReset = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_accelTime = NULL;
// event funtions
void ui_event_home2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // ui_accelScreen_screen_destroy();
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_accelReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        accelResetClicked(e);
    }
}

void ui_accelNewTime(float timeSec)
{
    char buf[7];

    snprintf(buf, sizeof(buf), "%.3fs", timeSec);
    lv_label_set_text(ui_accelTime, buf);
}

void ui_accelPhotogateStatus(int photogate_state, int photogate_state2){
    if (photogate_state) {
        lv_obj_add_state(ui_accelPhotoGate1Status, LV_STATE_CHECKED);     /// States
    } else {
        lv_obj_clear_state(ui_accelPhotoGate1Status, LV_STATE_CHECKED);     /// States
    }

    if (photogate_state2) {
        lv_obj_add_state(ui_accelPhotoGate2Status, LV_STATE_CHECKED);     /// States
    } else {
        lv_obj_clear_state(ui_accelPhotoGate2Status, LV_STATE_CHECKED);     /// States
    }
}

// build funtions

void ui_accelScreen_screen_init(void)
{
    ui_accelScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_accelScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_accelScreen);
    lv_obj_set_width(ui_Panel1, 383);
    lv_obj_set_height(ui_Panel1, 49);
    lv_obj_set_x(ui_Panel1, 202);
    lv_obj_set_y(ui_Panel1, -210);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xF5F330), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home2 = lv_btn_create(ui_accelScreen);
    lv_obj_set_width(ui_home2, 100);
    lv_obj_set_height(ui_home2, 32);
    lv_obj_set_x(ui_home2, -341);
    lv_obj_set_y(ui_home2, -216);
    lv_obj_set_align(ui_home2, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_accelScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -341);
    lv_obj_set_y(ui_Label3, -216);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Home");

    ui_accelPhotoGate1Status = lv_checkbox_create(ui_accelScreen);
    lv_checkbox_set_text(ui_accelPhotoGate1Status, "Photogate 1 ready");
    lv_obj_set_width(ui_accelPhotoGate1Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accelPhotoGate1Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accelPhotoGate1Status, 115);
    lv_obj_set_y(ui_accelPhotoGate1Status, -210);
    lv_obj_set_align(ui_accelPhotoGate1Status, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_accelPhotoGate1Status, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_accelPhotoGate2Status = lv_checkbox_create(ui_accelScreen);
    lv_checkbox_set_text(ui_accelPhotoGate2Status, "Photogate 2 ready");
    lv_obj_set_width(ui_accelPhotoGate2Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accelPhotoGate2Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accelPhotoGate2Status, 296);
    lv_obj_set_y(ui_accelPhotoGate2Status, -210);
    lv_obj_set_align(ui_accelPhotoGate2Status, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_accelPhotoGate2Status, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_accelReset = lv_btn_create(ui_accelScreen);
    lv_obj_set_width(ui_accelReset, 208);
    lv_obj_set_height(ui_accelReset, 92);
    lv_obj_set_x(ui_accelReset, 0);
    lv_obj_set_y(ui_accelReset, 150);
    lv_obj_set_align(ui_accelReset, LV_ALIGN_CENTER);

    ui_Label5 = lv_label_create(ui_accelScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 150);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Reset");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_accelScreen);
    lv_obj_set_width(ui_Panel2, 772);
    lv_obj_set_height(ui_Panel2, 260);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -40);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xCD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accelTime = lv_label_create(ui_accelScreen);
    lv_obj_set_width(ui_accelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accelTime, 0);
    lv_obj_set_y(ui_accelTime, -40);
    lv_obj_set_align(ui_accelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_accelTime, "0.000s");
    lv_obj_set_style_text_color(ui_accelTime, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_accelTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_home2, ui_event_home2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_accelReset, ui_event_accelReset, LV_EVENT_ALL, NULL);
    uic_accelScreen = ui_accelScreen;
    uic_accelPhotoGate1Status = ui_accelPhotoGate1Status;
    uic_accelPhotoGate2Status = ui_accelPhotoGate2Status;
    uic_accelReset = ui_accelReset;
    uic_accelTime = ui_accelTime;

}

void ui_accelScreen_screen_destroy(void)
{
    if(ui_accelScreen) lv_obj_del(ui_accelScreen);

    // NULL screen variables
    uic_accelScreen = NULL;
    ui_accelScreen = NULL;
    ui_Panel1 = NULL;
    ui_home2 = NULL;
    ui_Label3 = NULL;
    uic_accelPhotoGate1Status = NULL;
    ui_accelPhotoGate1Status = NULL;
    uic_accelPhotoGate2Status = NULL;
    ui_accelPhotoGate2Status = NULL;
    uic_accelReset = NULL;
    ui_accelReset = NULL;
    ui_Label5 = NULL;
    ui_Panel2 = NULL;
    uic_accelTime = NULL;
    ui_accelTime = NULL;

}
