// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: fsae-laptimer.spjj

#ifndef UI_ACCELSCREEN_H
#define UI_ACCELSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_accelScreen
extern void ui_accelScreen_screen_init(void);
extern void ui_accelScreen_screen_destroy(void);
extern lv_obj_t * ui_accelScreen;
extern lv_obj_t * ui_Panel1;
extern void ui_event_home2(lv_event_t * e);
extern lv_obj_t * ui_home2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_accelPhotoGate1Status;
extern lv_obj_t * ui_accelPhotoGate2Status;
extern void ui_event_accelReset(lv_event_t * e);
extern lv_obj_t * ui_accelReset;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_accelTime;
extern lv_obj_t * ui_lastTimesAccel;
extern lv_obj_t * ui_dropdownEquipeAccel;
extern lv_obj_t * ui_dropdownPilotoAccel;
extern lv_obj_t * ui_accelTimestamp;
// CUSTOM VARIABLES
extern lv_obj_t * uic_accelScreen;
extern lv_obj_t * uic_accelPhotoGate1Status;
extern lv_obj_t * uic_accelPhotoGate2Status;
extern lv_obj_t * uic_accelReset;
extern lv_obj_t * uic_accelTime;

#ifdef __cplusplus
} /*extern "C"*/
#endif

void ui_accelNewTime(float timeSec);
void ui_accelPhotogateStatus(int photogate_state, int photogate_state2);
void set_accel_button_text(uint8_t button_status);
bool ui_accelSelectionValid(void);
void ui_accelGetSelection(char *team_out, size_t team_out_len, int *driver_out);
void ui_accelResetDropdowns(void);
void ui_accelSetLastTimes(const char *text);
void ui_accelSetTimestamp(const char *text);


#endif

