// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: fsae-laptimer.spjj

#include "../ui.h"

lv_obj_t * uic_skidmain;
lv_obj_t * uic_accelmain;
lv_obj_t * uic_mainScreen;
lv_obj_t * ui_mainScreen = NULL;
lv_obj_t * ui_accelmain = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_skidmain = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_accelmain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_accelScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_accelScreen_screen_init);
        accelScreenLoaded();
    }
}

void ui_event_skidmain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_skidScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_skidScreen_screen_init);
        skidScreenLoaded();
    }
}

// build funtions

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_accelmain = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_accelmain, 223);
    lv_obj_set_height(ui_accelmain, 189);
    lv_obj_set_x(ui_accelmain, -154);
    lv_obj_set_y(ui_accelmain, 0);
    lv_obj_set_align(ui_accelmain, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -154);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Accel");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidmain = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_skidmain, 223);
    lv_obj_set_height(ui_skidmain, 189);
    lv_obj_set_x(ui_skidmain, 154);
    lv_obj_set_y(ui_skidmain, 0);
    lv_obj_set_align(ui_skidmain, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 154);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Skid");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_accelmain, ui_event_accelmain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_skidmain, ui_event_skidmain, LV_EVENT_ALL, NULL);
    uic_mainScreen = ui_mainScreen;
    uic_accelmain = ui_accelmain;
    uic_skidmain = ui_skidmain;

}

void ui_mainScreen_screen_destroy(void)
{
    if(ui_mainScreen) lv_obj_del(ui_mainScreen);

    // NULL screen variables
    uic_mainScreen = NULL;
    ui_mainScreen = NULL;
    uic_accelmain = NULL;
    ui_accelmain = NULL;
    ui_Label1 = NULL;
    uic_skidmain = NULL;
    ui_skidmain = NULL;
    ui_Label2 = NULL;

}
