// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: fsae-laptimer.spjj

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern lv_obj_t * ui_mainScreen;
extern void ui_event_accelmain(lv_event_t * e);
extern lv_obj_t * ui_accelmain;
extern lv_obj_t * ui_Label1;
extern void ui_event_skidmain(lv_event_t * e);
extern lv_obj_t * ui_skidmain;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_mainScreen;
extern lv_obj_t * uic_accelmain;
extern lv_obj_t * uic_skidmain;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

