// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: fsae-laptimer.spjj

#include "../ui.h"
#include <stdio.h>
#include <stdbool.h>

lv_obj_t * uic_skidTimeIdx5;
lv_obj_t * uic_skidTimeIdx4;
lv_obj_t * uic_skidTimeIdx3;
lv_obj_t * uic_skidTimeIdx2;
lv_obj_t * uic_skidTimeIdx1;
lv_obj_t * uic_skidAvg24;
lv_obj_t * uic_skidTime4;
lv_obj_t * uic_skidTime3;
lv_obj_t * uic_skidTime2;
lv_obj_t * uic_skidTime1;
lv_obj_t * uic_skidReset;
lv_obj_t * uic_skidScreen;
lv_obj_t * ui_skidScreen = NULL;
lv_obj_t * ui_home3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_skidPhotoGateStatus = NULL;
lv_obj_t * ui_skidReset = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_skidTime1 = NULL;
lv_obj_t * ui_skidTime2 = NULL;
lv_obj_t * ui_skidTime3 = NULL;
lv_obj_t * ui_skidTime4 = NULL;
lv_obj_t * ui_skidAvg24 = NULL;
lv_obj_t * ui_skidTimeIdx1 = NULL;
lv_obj_t * ui_skidTimeIdx2 = NULL;
lv_obj_t * ui_skidTimeIdx3 = NULL;
lv_obj_t * ui_skidTimeIdx4 = NULL;
lv_obj_t * ui_skidTimeIdx5 = NULL;

lv_obj_t **skidTimeLabels[5] = {&ui_skidTime1, &ui_skidTime2, &ui_skidTime3, &ui_skidTime4, &ui_skidAvg24};

// event funtions
void ui_event_home3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // ui_skidScreen_screen_destroy();
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_skidReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        for(int i = 0; i < 5; i++) {
            lv_label_set_text(*skidTimeLabels[i], "0.000s");
        }
        skidResetClicked(e);
    }
}

void ui_skidNewTime(float timeSec, uint16_t lapIdx)
{
    char buf[7];
    snprintf(buf, sizeof(buf), "%.3fs", timeSec);
    lv_label_set_text(*skidTimeLabels[lapIdx], buf);
}

void ui_skidPhotogateStatus(int photogate_state) {
    if (photogate_state) {
        lv_obj_add_state(ui_skidPhotoGateStatus, LV_STATE_CHECKED);     /// States
    } else {
        lv_obj_clear_state(ui_skidPhotoGateStatus, LV_STATE_CHECKED);     /// States
    }
}

// build funtions

void ui_skidScreen_screen_init(void)
{
    ui_skidScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_skidScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home3 = lv_btn_create(ui_skidScreen);
    lv_obj_set_width(ui_home3, 100);
    lv_obj_set_height(ui_home3, 32);
    lv_obj_set_x(ui_home3, -341);
    lv_obj_set_y(ui_home3, -216);
    lv_obj_set_align(ui_home3, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -341);
    lv_obj_set_y(ui_Label4, -216);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Home");

    ui_Panel3 = lv_obj_create(ui_skidScreen);
    lv_obj_set_width(ui_Panel3, 193);
    lv_obj_set_height(ui_Panel3, 49);
    lv_obj_set_x(ui_Panel3, 297);
    lv_obj_set_y(ui_Panel3, -210);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xF5F330), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidPhotoGateStatus = lv_checkbox_create(ui_skidScreen);
    lv_checkbox_set_text(ui_skidPhotoGateStatus, "Photogate ready");
    lv_obj_set_width(ui_skidPhotoGateStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidPhotoGateStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidPhotoGateStatus, 297);
    lv_obj_set_y(ui_skidPhotoGateStatus, -210);
    lv_obj_set_align(ui_skidPhotoGateStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skidPhotoGateStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_skidReset = lv_btn_create(ui_skidScreen);
    lv_obj_set_width(ui_skidReset, 208);
    lv_obj_set_height(ui_skidReset, 92);
    lv_obj_set_x(ui_skidReset, 0);
    lv_obj_set_y(ui_skidReset, 150);
    lv_obj_set_align(ui_skidReset, LV_ALIGN_CENTER);

    ui_Label6 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 150);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Reset");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_skidScreen);
    lv_obj_set_width(ui_Panel4, 772);
    lv_obj_set_height(ui_Panel4, 260);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -40);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xCD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTime1 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTime1, -100);
    lv_obj_set_y(ui_skidTime1, -130);
    lv_obj_set_align(ui_skidTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTime1, "0.000s");
    lv_obj_set_style_text_color(ui_skidTime1, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTime1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTime2 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTime2, -100);
    lv_obj_set_y(ui_skidTime2, -70);
    lv_obj_set_align(ui_skidTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTime2, "0.000s");
    lv_obj_set_style_text_color(ui_skidTime2, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTime2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTime3 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTime3, -100);
    lv_obj_set_y(ui_skidTime3, -10);
    lv_obj_set_align(ui_skidTime3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTime3, "0.000s");
    lv_obj_set_style_text_color(ui_skidTime3, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTime3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTime3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTime4 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTime4, -100);
    lv_obj_set_y(ui_skidTime4, 50);
    lv_obj_set_align(ui_skidTime4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTime4, "0.000s");
    lv_obj_set_style_text_color(ui_skidTime4, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTime4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTime4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidAvg24 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidAvg24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidAvg24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidAvg24, 190);
    lv_obj_set_y(ui_skidAvg24, -40);
    lv_obj_set_align(ui_skidAvg24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidAvg24, "0.000s");
    lv_obj_set_style_text_color(ui_skidAvg24, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidAvg24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidAvg24, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTimeIdx1 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTimeIdx1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTimeIdx1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTimeIdx1, -280);
    lv_obj_set_y(ui_skidTimeIdx1, -130);
    lv_obj_set_align(ui_skidTimeIdx1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTimeIdx1, "Volta 1:");
    lv_obj_set_style_text_color(ui_skidTimeIdx1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTimeIdx1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTimeIdx1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTimeIdx2 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTimeIdx2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTimeIdx2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTimeIdx2, -280);
    lv_obj_set_y(ui_skidTimeIdx2, -70);
    lv_obj_set_align(ui_skidTimeIdx2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTimeIdx2, "Volta 2:");
    lv_obj_set_style_text_color(ui_skidTimeIdx2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTimeIdx2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTimeIdx2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTimeIdx3 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTimeIdx3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTimeIdx3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTimeIdx3, -280);
    lv_obj_set_y(ui_skidTimeIdx3, -10);
    lv_obj_set_align(ui_skidTimeIdx3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTimeIdx3, "Volta 3:");
    lv_obj_set_style_text_color(ui_skidTimeIdx3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTimeIdx3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTimeIdx3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTimeIdx4 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTimeIdx4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTimeIdx4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTimeIdx4, -280);
    lv_obj_set_y(ui_skidTimeIdx4, 50);
    lv_obj_set_align(ui_skidTimeIdx4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTimeIdx4, "Volta 4:");
    lv_obj_set_style_text_color(ui_skidTimeIdx4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTimeIdx4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTimeIdx4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skidTimeIdx5 = lv_label_create(ui_skidScreen);
    lv_obj_set_width(ui_skidTimeIdx5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skidTimeIdx5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_skidTimeIdx5, 190);
    lv_obj_set_y(ui_skidTimeIdx5, -106);
    lv_obj_set_align(ui_skidTimeIdx5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skidTimeIdx5, "Media 2 & 4");
    lv_obj_set_style_text_color(ui_skidTimeIdx5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skidTimeIdx5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skidTimeIdx5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_home3, ui_event_home3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_skidReset, ui_event_skidReset, LV_EVENT_ALL, NULL);
    uic_skidScreen = ui_skidScreen;
    uic_skidReset = ui_skidReset;
    uic_skidTime1 = ui_skidTime1;
    uic_skidTime2 = ui_skidTime2;
    uic_skidTime3 = ui_skidTime3;
    uic_skidTime4 = ui_skidTime4;
    uic_skidAvg24 = ui_skidAvg24;
    uic_skidTimeIdx1 = ui_skidTimeIdx1;
    uic_skidTimeIdx2 = ui_skidTimeIdx2;
    uic_skidTimeIdx3 = ui_skidTimeIdx3;
    uic_skidTimeIdx4 = ui_skidTimeIdx4;
    uic_skidTimeIdx5 = ui_skidTimeIdx5;

}

void ui_skidScreen_screen_destroy(void)
{
    if(ui_skidScreen) lv_obj_del(ui_skidScreen);

    // NULL screen variables
    uic_skidScreen = NULL;
    ui_skidScreen = NULL;
    ui_home3 = NULL;
    ui_Label4 = NULL;
    ui_Panel3 = NULL;
    ui_skidPhotoGateStatus = NULL;
    uic_skidReset = NULL;
    ui_skidReset = NULL;
    ui_Label6 = NULL;
    ui_Panel4 = NULL;
    uic_skidTime1 = NULL;
    ui_skidTime1 = NULL;
    uic_skidTime2 = NULL;
    ui_skidTime2 = NULL;
    uic_skidTime3 = NULL;
    ui_skidTime3 = NULL;
    uic_skidTime4 = NULL;
    ui_skidTime4 = NULL;
    uic_skidAvg24 = NULL;
    ui_skidAvg24 = NULL;
    uic_skidTimeIdx1 = NULL;
    ui_skidTimeIdx1 = NULL;
    uic_skidTimeIdx2 = NULL;
    ui_skidTimeIdx2 = NULL;
    uic_skidTimeIdx3 = NULL;
    ui_skidTimeIdx3 = NULL;
    uic_skidTimeIdx4 = NULL;
    ui_skidTimeIdx4 = NULL;
    uic_skidTimeIdx5 = NULL;
    ui_skidTimeIdx5 = NULL;

}
