// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: fsae-laptimer.spjj

#ifndef UI_SKIDSCREEN_H
#define UI_SKIDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_skidScreen
extern void ui_skidScreen_screen_init(void);
extern void ui_skidScreen_screen_destroy(void);
extern lv_obj_t * ui_skidScreen;
extern void ui_event_home3(lv_event_t * e);
extern lv_obj_t * ui_home3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_skidPhotoGateStatus;
extern void ui_event_skidReset(lv_event_t * e);
extern lv_obj_t * ui_skidReset;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_skidTime1;
extern lv_obj_t * ui_skidTime2;
extern lv_obj_t * ui_skidTime3;
extern lv_obj_t * ui_skidTime4;
extern lv_obj_t * ui_skidAvg24;
extern lv_obj_t * ui_skidTimeIdx1;
extern lv_obj_t * ui_skidTimeIdx2;
extern lv_obj_t * ui_skidTimeIdx3;
extern lv_obj_t * ui_skidTimeIdx4;
extern lv_obj_t * ui_skidTimeIdx5;
extern lv_obj_t * ui_LastTimesSkid;
extern lv_obj_t * ui_dropdownEquipeSkid;
extern lv_obj_t * ui_dropdownPilotoSkid;
// CUSTOM VARIABLES
extern lv_obj_t * uic_skidScreen;
extern lv_obj_t * uic_skidReset;
extern lv_obj_t * uic_skidTime1;
extern lv_obj_t * uic_skidTime2;
extern lv_obj_t * uic_skidTime3;
extern lv_obj_t * uic_skidTime4;
extern lv_obj_t * uic_skidAvg24;
extern lv_obj_t * uic_skidTimeIdx1;
extern lv_obj_t * uic_skidTimeIdx2;
extern lv_obj_t * uic_skidTimeIdx3;
extern lv_obj_t * uic_skidTimeIdx4;
extern lv_obj_t * uic_skidTimeIdx5;

void ui_skidNewTime(float timeSec, uint16_t lapIdx);
void ui_skidPhotogateStatus(int photogate_state);
void set_button_text(uint8_t button_status);
void ui_skidClearTimes(void);
bool ui_skidSelectionValid(void);
void ui_skidGetSelection(char *team_out, size_t team_out_len, int *driver_out);
void ui_skidResetDropdowns(void);
void ui_skidSetLastTimes(const char *text);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

